AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ideaslabut-aws-lambda

  Template for `ideaslabut-aws-lambda` which creates lambda function to invoke execute api for websocket connections

Parameters:
  OpenSearchUrl:
    Type: String
    Description: (Required) The OpenSearch URL
  BuildCodeUri:
    Type: String
    Description: (Required) The code uri
  FunctionName:
    Type: String
    Description: (Optional) The name of the lambda function
    Default: 'ideaslabut-websocket-lambda'

Resources:
  WebSocketLambdaFunction:
    properties:
      FunctionName: !Ref functionName
      Architectures:
        - 'x86_64'
      Handler: 'org.ideaslabut.aws.lambda.handlers.WebSocketMessageHandler'
      Environment:
        elasticsearch.url: !Ref OpenSearchUrl
      CodeUri: !Sub '../websocket-lambda/build/libs/${BuildCodeUri}'
      MemorySize: 256
      Runtime: java11
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SimpleChatWebSocket}/*'