AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ideaslabut-aws-lambda

  Template for `ideaslabut-aws-lambda` which creates lambda function to invoke execute api for websocket connections

Parameters:
  OpenSearchUrl:
    Type: String
    Description: (Required) The OpenSearch URL
  WebSocketManagementUrl:
    Type: String
    Description: (Required) The OpenSearch URL
  FunctionName:
    Type: String
    Description: (Required) The name of the lambda function
  MasterUserName:
    Type: String
    Description: (Required) Master user name for open search
  MasterUserPassword:
    Type: String
    Description: (Required) Master password for elasticsearch

Resources:
  WebSocketLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../websocket-lambda/build/libs/websocket-lambda-1.0.0-SNAPSHOT.zip
      FunctionName: !Ref FunctionName
      Architectures:
        - x86_64
      Handler: org.ideaslabut.aws.lambda.handlers.WebSocketMessageHandler
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1'
          WEBSOCKET_MANAGEMENT_URL: !Ref WebSocketManagementUrl
          ELASTICSEARCH_URL: !Ref OpenSearchUrl
          ELASTICSEARCH_AUTHENTICATION_KEY:
                                Fn::Base64: !Sub ${MasterUserName}:${MasterUserPassword}
      MemorySize: 500
      Timeout: 10
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess

Outputs:
  WebSocketLambdaFunctionName:
    Value: !Ref WebSocketLambdaFunction
  WebSocketLambdaFunctionArn:
    Value: !GetAtt WebSocketLambdaFunction.Arn