AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ideaslabut-aws-lambda
  Template for `ideaslabut-aws-lambda` which creates lambda function to invoke execute api for websocket connections

Parameters:
  MasterUserName:
    Type: String
    Description: (Required) The master username for OpenSearch instance
  MasterUserPassword:
    Type: String
    Description: (Required) The msater password for OpenSearch Instance

Resources:
  WearablesOpenSearchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: opensearch.yml
      Parameters:
        MasterUserName: !Ref MasterUserName
        MasterUserPassword: !Ref MasterUserPassword

  WearablesLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda.yml
      Parameters:
        MasterUserName: !Ref MasterUserName
        MasterUserPassword: !Ref MasterUserPassword
        OpenSearchUrl: !GetAtt WearablesOpenSearchStack.Outputs.DomainEndpoint

  WearablesWebSocketApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apigateway-websocket.yml
      Parameters:
        WebSocketLambdaFunctionName: !GetAtt WearablesLambdaStack.Outputs.WebSocketLambdaFunctionName
        WebSocketLambdaFunctionArn: !GetAtt WearablesLambdaStack.Outputs.WebSocketLambdaFunctionArn