AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ideaslabut-aws-lambda
  Template for `ideaslabut-aws-lambda` which creates lambda function to invoke execute api for websocket connections

Parameters:
  MasterUserName:
    Type: String
    Description: (Required) The master username for OpenSearch instance
  MasterUserPassword:
    Type: String
    Description: (Required) The msater password for OpenSearch Instance
  FunctionName:
    Type: String
    Description: (Required) The name of the lambda function

Resources:
  WearablesOpenSearchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: opensearch.yml
      Parameters:
        MasterUserName: !Ref MasterUserName
        MasterUserPassword: !Ref MasterUserPassword

  WearablesWebSocketApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apigateway-websocket.yml
      Parameters:
        WebSocketLambdaFunctionName: !Ref FunctionName

  WearablesLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda.yml
      Parameters:
        MasterUserName: !Ref MasterUserName
        MasterUserPassword: !Ref MasterUserPassword
        FunctionName: !Ref FunctionName
        WebSocketManagementUrl: !GetAtt WearablesWebSocketApiGatewayStack.Outputs.WearablesWebSocketManagementUrl
        OpenSearchUrl: !GetAtt WearablesOpenSearchStack.Outputs.DomainEndpoint

  LamdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WearablesLambdaStack.Outputs.WebSocketLambdaFunctionArn
      Principal: apigateway.amazonaws.com

